[package]
name = "cargo-testf"
version = "0.1.0"
edition = "2021"
description = "A wrapper for `cargo test` that remembers and runs failed tests"

[dependencies]
# no dependency to be added to maintain a thin profile.
